services:
  Nginx:
    container_name: "Nginx"
    restart: always
    image: "nginx"
    volumes:
      - "./html:/usr/share/nginx/html:ro"
      - "./config/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "80:80"
