services:
  availabilitysite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "AvailabilitySite"
    volumes:
      - ./Site:/var/www/html:ro
    networks:
      - "Frontend"
      - "AvailabilityBackend"
    depends_on:
      - AvailabilityDB
    ports:
      - 80:80

  AvailabilityDB:
    image: mysql
    container_name: "AvailabilityDB"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - "AvailabilityBackend"

networks:
  Frontend:
    driver: bridge
  AvailabilityBackend:
    driver: bridge
